### ISSUE TITLE
Struts 1.x and Tiles plugin not work in Intellij Idea 2019.3

### ISSUE THREAD

**Issue by Patriqu** [JetBrains/intellij-obsolete-plugins#1]
Struts 1.x and Tiles plugin does not working in Intellij Idea 2019.3 Ultimate Edition. Plugin in version 192.8 is placed in config/plugins/struts/lib directory of the 2019.3 version. In 2019.2.4 Ultimate Edition plugin works as expected and is listed on the plugins window. Does support for this plugin in the newer versions of Intellij has been dropped? We still use those obsolete framework in our projects.

**Comment by yole** [comment]
What does "does not working" mean exactly?

**Comment by yole** [comment]
I've published a version of the plugin compatible with 2019.3 to the plugin manager. I can't promise that we'll be able to keep the plugin working in 2020.1, but for now you should still be able to use it.

**Comment by Patriqu** [comment]
Thank you. It works now. It helps to quickly resolve beans and action mappings in the project.
