### ISSUE TITLE
J2ME Plugin doesn't work with J2ME SDK 3.0.5

### ISSUE THREAD

**Issue by MadRatSRP** [JetBrains/intellij-obsolete-plugins#3]
When i already installed it and trying to select it manually, Intellij Idea tells me this: "The selected directory is not a valid home for mobile sdk". But when i do the same with directory with J2ME Wireless Toolkit 2.2 it finds it perfectly and initializes as SDK. Am I doing something wrong?

**Comment by yole** [comment]
The J2ME plugin is unsupported. If it doesn't work in any specific configuration, that's unfortunate, but we have no plans to investigate the issue or provide fixes.

**Comment by MadRatSRP** [comment]
Okay, then can i fork your repository and publish modified version as another plugin to Jetbrains plugins repository? I would like to fix it so it could be usable with SDKs other than WTK

**Comment by yole** [comment]
Yes, you're welcome to do that.

**Comment by MadRatSRP** [comment]
Thanks

**Comment by MadRatSRP** [comment]
I'm sorry for stupid question, but what is the main class of J2ME module and should i use Application configuration or Ant to build it?

**Comment by elmot** [comment]
@MadRatSRP probably this is for you
https://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system.html

**Comment by MadRatSRP** [comment]
> @MadRatSRP probably this is for you
> https://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system.html

Thank you!
